mysql:
  # 用户名
  username: root
  # 密码
  password: root
  # 数据库名
  database: gin_web
  # 主机地址(地址改为docker内网地址, 参见gin-web-docker项目docker-compose.yml配置)
  host: docker-mysql-db
  # 端口
  port: 3306
  # 连接字符串查询参数
  query: charset=utf8&parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: false
  # 数据库表前缀
  table-prefix: tb_